# Site Info
title:              "Diar Selimi"
description:        "This blog will contain everything that I learn and every problem that I solve will be secribed here."
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-55839922-3 # Put your Google Analytics code

# Author Info
author_name:        "Diar Selimi" # Your name here
author_email:       diarselimi92@gmail.com # Your email here
author_gravatar:    8c03827422592572104af48f0fecb627 # Your Gravatar md5 hash here for logo
twitter_username:   diarselimi92 # Your Twitter username here
github_username:    Diarselimi # Your GitHub username here

# Site Settings
url:                https://diarselimi.github.io # main url
baseurl:            / # for gh-pages
permalink:          /notes/:title # Post permalink
timezone:           Europe/Belgrade # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
